Profile page
Turplanlegger/turplanlegger-webui pull request #143
Opened 2023-10-03 18:26 UTC by crazycatman

* Added profile page
  * Display user first and last name
  * Display joined date
  * User can toggle private mode
  * Profile picture
    * Changes based on profile visibility

2023-10-03 18:38 UTC, peseb requested changes

2023-10-03 18:38 UTC, peseb commented on src/pages/Users/Profile.tsx
> +  // const user = useRecoilValue(whoamiState);
```suggestion
```

2023-10-03 18:38 UTC, peseb commented on src/pages/Users/Profile.tsx
> +          Name: {user.name} {user.last_name}
Putte Name og Joined i translation? :D

2023-10-03 19:53 UTC, crazycatman commented on src/pages/Users/Profile.tsx
> +  // const user = useRecoilValue(whoamiState);
Fixed

2023-10-03 19:53 UTC, crazycatman commented on src/pages/Users/Profile.tsx
> +          Name: {user.name} {user.last_name}
Fixed

2023-11-07 17:34 UTC, sixcare requested changes

2023-11-07 18:07 UTC, merged